[2019-02-10 19:32:08,495] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:29:35.131814+00:00 [queued]>
[2019-02-10 19:32:08,499] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:29:35.131814+00:00 [queued]>
[2019-02-10 19:32:08,499] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:32:08,507] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2019-02-10T19:29:35.131814+00:00
[2019-02-10 19:32:08,507] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2019-02-10T19:29:35.131814+00:00 --job_id 98 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmpniwy9k62']
[2019-02-10 19:32:09,040] {base_task_runner.py:101} INFO - Job 98: Subtask Data_to_SQL [2019-02-10 19:32:09,040] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:32:09,194] {base_task_runner.py:101} INFO - Job 98: Subtask Data_to_SQL [2019-02-10 19:32:09,194] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:32:09,207] {base_task_runner.py:101} INFO - Job 98: Subtask Data_to_SQL [2019-02-10 19:32:09,207] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:29:35.131814+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:32:09,217] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 19:32:09,217] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2019-02-10T19:29:35.131814+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-02-10T19:29:35.131814+00:00
[2019-02-10 19:32:09,218] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmpjyu78qug/Data_to_SQLx20win4e
[2019-02-10 19:32:09,219] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 19:32:09,222] {bash_operator.py:119} INFO - Output:
[2019-02-10 19:32:09,227] {bash_operator.py:123} INFO - ERROR 2 (HY000) at line 1: File '/home/ec2-user/rescale/data/*' not found (Errcode: 2 - No such file or directory)
[2019-02-10 19:32:09,227] {bash_operator.py:127} INFO - Command exited with return code 0
[2019-02-10 19:32:13,495] {logging_mixin.py:95} INFO - [2019-02-10 19:32:13,495] {jobs.py:2527} INFO - Task exited with return code 0
