[2019-02-10 19:28:22,229] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:26:20.406189+00:00 [queued]>
[2019-02-10 19:28:22,233] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:26:20.406189+00:00 [queued]>
[2019-02-10 19:28:22,234] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:28:22,241] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2019-02-10T19:26:20.406189+00:00
[2019-02-10 19:28:22,241] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2019-02-10T19:26:20.406189+00:00 --job_id 88 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmpi016ae6x']
[2019-02-10 19:28:22,780] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL [2019-02-10 19:28:22,780] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:28:22,934] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL [2019-02-10 19:28:22,933] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:28:22,946] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL [2019-02-10 19:28:22,945] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2019-02-10T19:26:20.406189+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:28:22,956] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 19:28:22,956] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2019-02-10T19:26:20.406189+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-02-10T19:26:20.406189+00:00
[2019-02-10 19:28:22,957] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmpfmxqlh_i/Data_to_SQLjwc25o0n
[2019-02-10 19:28:22,957] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 19:28:22,960] {bash_operator.py:119} INFO - Output:
[2019-02-10 19:28:22,961] {bash_operator.py:123} INFO - /tmp/airflowtmpfmxqlh_i/Data_to_SQLjwc25o0n: line 1: /home/ec2-user/insert_to_sql.sh: Permission denied
[2019-02-10 19:28:22,961] {bash_operator.py:127} INFO - Command exited with return code 126
[2019-02-10 19:28:22,966] {models.py:1788} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 19:28:22,967] {models.py:1811} INFO - Marking task as UP_FOR_RETRY
[2019-02-10 19:28:22,978] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL Traceback (most recent call last):
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/bin/airflow", line 32, in <module>
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     args.func(args)
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     return f(*args, **kwargs)
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     _run(args, dag, ti)
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     pool=args.pool,
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     return func(*args, **kwargs)
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     result = task_copy.execute(context=context)
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL     raise AirflowException("Bash command failed")
[2019-02-10 19:28:22,979] {base_task_runner.py:101} INFO - Job 88: Subtask Data_to_SQL airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 19:28:27,229] {logging_mixin.py:95} INFO - [2019-02-10 19:28:27,229] {jobs.py:2527} INFO - Task exited with return code 1
