[2019-02-10 19:45:12,885] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-07-02T00:00:00+00:00 [queued]>
[2019-02-10 19:45:12,889] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-07-02T00:00:00+00:00 [queued]>
[2019-02-10 19:45:12,889] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:45:12,898] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2015-07-02T00:00:00+00:00
[2019-02-10 19:45:12,898] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2015-07-02T00:00:00+00:00 --job_id 118 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmpmz3ya81w']
[2019-02-10 19:45:13,606] {base_task_runner.py:101} INFO - Job 118: Subtask Data_to_SQL [2019-02-10 19:45:13,606] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:45:13,857] {base_task_runner.py:101} INFO - Job 118: Subtask Data_to_SQL [2019-02-10 19:45:13,856] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:45:13,873] {base_task_runner.py:101} INFO - Job 118: Subtask Data_to_SQL [2019-02-10 19:45:13,873] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2015-07-02T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:45:13,885] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 19:45:13,886] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2015-07-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-07-02T00:00:00+00:00
[2019-02-10 19:45:13,886] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmp0algmznz/Data_to_SQL1vbc66kr
[2019-02-10 19:45:13,886] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 19:45:13,890] {bash_operator.py:119} INFO - Output:
[2019-02-10 19:45:13,978] {bash_operator.py:123} INFO - /home/ec2-user/insert_to_sql.sh: line 4: GO: command not found
[2019-02-10 19:45:17,162] {bash_operator.py:127} INFO - Command exited with return code 0
[2019-02-10 19:45:17,896] {logging_mixin.py:95} INFO - [2019-02-10 19:45:17,896] {jobs.py:2527} INFO - Task exited with return code 0
