[2019-02-10 19:23:19,297] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-13T00:00:00+00:00 [queued]>
[2019-02-10 19:23:19,302] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-13T00:00:00+00:00 [queued]>
[2019-02-10 19:23:19,302] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:23:19,310] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2015-06-13T00:00:00+00:00
[2019-02-10 19:23:19,310] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2015-06-13T00:00:00+00:00 --job_id 72 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmpm6tv_ayq']
[2019-02-10 19:23:19,843] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL [2019-02-10 19:23:19,842] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:23:19,994] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL [2019-02-10 19:23:19,994] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:23:20,007] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL [2019-02-10 19:23:20,006] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2015-06-13T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:23:20,019] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 19:23:20,019] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2015-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-06-13T00:00:00+00:00
[2019-02-10 19:23:20,019] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmp868m96d9/Data_to_SQLhptpyr7e
[2019-02-10 19:23:20,020] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 19:23:20,023] {bash_operator.py:119} INFO - Output:
[2019-02-10 19:23:20,024] {bash_operator.py:123} INFO - /tmp/airflowtmp868m96d9/Data_to_SQLhptpyr7e: line 1: /home/ec2-user/insert_to_sql.sh: Permission denied
[2019-02-10 19:23:20,024] {bash_operator.py:127} INFO - Command exited with return code 126
[2019-02-10 19:23:20,030] {models.py:1788} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 19:23:20,031] {models.py:1817} INFO - All retries failed; marking task as FAILED
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL Traceback (most recent call last):
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/bin/airflow", line 32, in <module>
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     args.func(args)
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     return f(*args, **kwargs)
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     _run(args, dag, ti)
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     pool=args.pool,
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     return func(*args, **kwargs)
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     result = task_copy.execute(context=context)
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
[2019-02-10 19:23:20,043] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL     raise AirflowException("Bash command failed")
[2019-02-10 19:23:20,044] {base_task_runner.py:101} INFO - Job 72: Subtask Data_to_SQL airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 19:23:24,298] {logging_mixin.py:95} INFO - [2019-02-10 19:23:24,297] {jobs.py:2527} INFO - Task exited with return code 1
