[2019-02-10 19:30:17,346] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-23T00:00:00+00:00 [queued]>
[2019-02-10 19:30:17,351] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-23T00:00:00+00:00 [queued]>
[2019-02-10 19:30:17,351] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:30:17,359] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2015-06-23T00:00:00+00:00
[2019-02-10 19:30:17,359] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2015-06-23T00:00:00+00:00 --job_id 95 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmpsj88ttmp']
[2019-02-10 19:30:17,896] {base_task_runner.py:101} INFO - Job 95: Subtask Data_to_SQL [2019-02-10 19:30:17,896] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:30:18,050] {base_task_runner.py:101} INFO - Job 95: Subtask Data_to_SQL [2019-02-10 19:30:18,049] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:30:18,062] {base_task_runner.py:101} INFO - Job 95: Subtask Data_to_SQL [2019-02-10 19:30:18,061] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2015-06-23T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:30:18,072] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 19:30:18,072] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2015-06-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-06-23T00:00:00+00:00
[2019-02-10 19:30:18,073] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmpek518iap/Data_to_SQLf5dhslbh
[2019-02-10 19:30:18,073] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 19:30:18,076] {bash_operator.py:119} INFO - Output:
[2019-02-10 19:30:18,081] {bash_operator.py:123} INFO - ERROR 2 (HY000) at line 1: File '/home/ec2-user/rescale/data/*' not found (Errcode: 2 - No such file or directory)
[2019-02-10 19:30:18,082] {bash_operator.py:127} INFO - Command exited with return code 0
[2019-02-10 19:30:22,346] {logging_mixin.py:95} INFO - [2019-02-10 19:30:22,346] {jobs.py:2527} INFO - Task exited with return code 0
