[2019-02-10 20:09:02,519] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-07-21T00:00:00+00:00 [queued]>
[2019-02-10 20:09:02,523] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-07-21T00:00:00+00:00 [queued]>
[2019-02-10 20:09:02,523] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 20:09:02,531] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2015-07-21T00:00:00+00:00
[2019-02-10 20:09:02,531] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2015-07-21T00:00:00+00:00 --job_id 162 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmp4f3bikco']
[2019-02-10 20:09:03,066] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL [2019-02-10 20:09:03,066] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 20:09:03,218] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL [2019-02-10 20:09:03,218] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 20:09:03,231] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL [2019-02-10 20:09:03,230] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2015-07-21T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 20:09:03,241] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 20:09:03,242] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Data_to_SQL
AIRFLOW_CTX_EXECUTION_DATE=2015-07-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-07-21T00:00:00+00:00
[2019-02-10 20:09:03,242] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmppl1hkwam/Data_to_SQL7gkvli6q
[2019-02-10 20:09:03,242] {bash_operator.py:110} INFO - Running command: /home/ec2-user/insert_to_sql.sh 
[2019-02-10 20:09:03,245] {bash_operator.py:119} INFO - Output:
[2019-02-10 20:09:03,247] {bash_operator.py:123} INFO - /tmp/airflowtmppl1hkwam/Data_to_SQL7gkvli6q: line 1: /home/ec2-user/insert_to_sql.sh: No such file or directory
[2019-02-10 20:09:03,247] {bash_operator.py:127} INFO - Command exited with return code 127
[2019-02-10 20:09:03,251] {models.py:1788} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 20:09:03,253] {models.py:1811} INFO - Marking task as UP_FOR_RETRY
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL Traceback (most recent call last):
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/bin/airflow", line 32, in <module>
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     args.func(args)
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     return f(*args, **kwargs)
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     _run(args, dag, ti)
[2019-02-10 20:09:03,264] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     pool=args.pool,
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     return func(*args, **kwargs)
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     result = task_copy.execute(context=context)
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL     raise AirflowException("Bash command failed")
[2019-02-10 20:09:03,265] {base_task_runner.py:101} INFO - Job 162: Subtask Data_to_SQL airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 20:09:07,520] {logging_mixin.py:95} INFO - [2019-02-10 20:09:07,520] {jobs.py:2527} INFO - Task exited with return code 1
